In [3]:
import os
import pandas as pd

In [18]:
barcode_dir = f"{os.getcwd()}/../data/htseq-count/"

In [19]:
files = os.listdir(barcode_dir)

In [25]:
df = pd.read_csv(barcode_dir + "donor_ids.tsv", delimiter="\t")

In [26]:
df.head()

,cell,donor_id,prob_max,prob_doublet,n_vars,best_singlet,best_doublet,doublet_logLikRatio
0,AAACCCAAGCTCCATA-1,donor3,1.000000e+00,1.590000e-92,1436,donor3,"donor0,donor3",-208.215
1,AAACCCACAAATACGA-1,donor1,1.000000e+00,2.860000e-174,3192,donor1,"donor1,donor0",-396.440
2,AAACCCAGTCATCACA-1,donor1,1.000000e+00,1.210000e-28,99,donor1,"donor1,donor0",-61.122
3,AAACCCATCATTCGGA-1,donor3,1.000000e+00,0.000000e+00,4057,donor3,"donor0,donor1",-1538.931
4,AAACGAACAGCTGTGC-1,doublet,8.510000e-10,1.000000e+00,371,donor2,"donor1,donor0",24.043

In [31]:
df = df[["cell", "donor_id"]]

In [32]:
df["donor_id"].value_counts()

donor_id
donor3        2236
donor1        1360
donor2        1235
doublet        545
donor0         416
unassigned     200
Name: count, dtype: int64

In [33]:
df_pool1 = df[df["donor_id"] == "donor1"]

In [36]:
df_pool1.head()

                  cell donor_id
1   AAACCCACAAATACGA-1   donor1
2   AAACCCAGTCATCACA-1   donor1
8   AAACGAATCACGACTA-1   donor1
10  AAACGAATCCTTATGT-1   donor1
11  AAACGAATCCTTTAGT-1   donor1