In [2]:
# pip install gseapy

In [1]:
import pandas as pd
from gseapy.plot import gseaplot
import gseapy as gp
import numpy as np

In [16]:
dea_df = pd.read_csv("de_genes_bulk_rrna-.csv")
dea_df = dea_df.rename(columns={"Unnamed: 0": "gene"})

In [17]:
dea_df["rank"] = -np.log10(dea_df["padj"])*dea_df["log2FoldChange"]

In [24]:
dea_df = dea_df.sort_values("rank", ascending=False).reset_index(drop=True)

In [28]:
dea_df.head()

,gene,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,rank
0,BARX1,31.373488,3.739755,0.750145,4.985375,6.184171e-07,0.000754,11.677979
1,ITPR2-AS1,116.289046,3.414676,0.650911,5.245998,1.554383e-07,0.000400,11.602628
2,ENSG00000248935,16.328000,4.774394,1.048520,4.553460,5.277077e-06,0.004366,11.267337
3,PTPRT,547.900619,4.572006,1.013815,4.509704,6.491825e-06,0.004557,10.704592
4,KRTAP2-3,43.573226,4.324028,0.937853,4.610563,4.015797e-06,0.003578,10.578252

In [26]:
ranking = dea_df[["gene", "rank"]]

In [27]:
ranking

                gene       rank
0              BARX1  11.677979
1          ITPR2-AS1  11.602628
2    ENSG00000248935  11.267337
3              PTPRT  10.704592
4           KRTAP2-3  10.578252
..               ...        ...
143          ATP13A4 -17.079744
144            ENPP6 -18.378015
145          PCDH11X -39.066608
146        LINC01391 -48.119902
147             STAR -78.437243

[148 rows x 2 columns]

In [31]:
adiposite_genes = pd.read_excel("emont2022s1.xlsx", sheet_name="adipocyte markers", header=1)

In [35]:
adiposite_genes = list(adiposite_genes["Unnamed: 0"])

In [39]:
adiposite_genes[:5]

['NAV2', 'AC018616.1', 'FABP4', 'MAPK10', 'ITLN1']

In [44]:
shared_genes = list(set(ranking["gene"])&set(adiposite_genes))

In [45]:
dea_df[dea_df["gene"].isin(shared_genes)]

,gene,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,rank
21,C1QB,1067.567397,2.355934,0.583152,4.040001,5.345107e-05,0.022929,3.862846
38,C1QA,901.652756,2.274480,0.589752,3.856674,1.149403e-04,0.032029,3.399097
52,IRF8,1345.462125,1.926645,0.517227,3.724948,1.953552e-04,0.038753,2.719840
60,HLA-DRA,6761.786297,1.585437,0.413956,3.829968,1.281599e-04,0.032623,2.356714
74,ANKRD36C,2054.900795,-0.744448,0.190995,-3.897734,9.709682e-05,0.029989,-1.133825
78,LTBP1,1274.218556,-1.266203,0.331862,-3.815453,1.359333e-04,0.033403,-1.869191
79,RNF217-AS1,38.144004,-1.245789,0.310311,-4.014650,5.953403e-05,0.024380,-2.009419
84,CTH,172.687153,-1.868675,0.511580,-3.652750,2.594464e-04,0.044517,-2.525463
96,CRNDE,310.567102,-2.095019,0.523868,-3.999131,6.357543e-05,0.024893,-3.360248
108,TMEFF2,17.259625,-2.446781,0.630635,-3.879869,1.045128e-04,0.030645,-3.703556
112,MKX,90.415565,-2.624962,0.688795,-3.810951,1.384334e-04,0.033403,-3.875014
116,ACADL,35.350559,-2.909873,0.732250,-3.973881,7.071101e-05,0.026419,-4.592045
131,MME,140.174510,-2.386054,0.458660,-5.202228,1.969133e-07,0.000415,-8.070362
138,PCSK6,169.448788,-2.594488,0.427311,-6.071658,1.265960e-09,0.000006,-13.573678

In [ ]:
adiposite_genes

In [37]:
pre_res = gp.prerank(
    rnk=ranking,
    gene_sets={"my_set": adiposite_genes},
    seed=2,
    weight=
)

AttributeError: 'datetime.datetime' object has no attribute 'isupper'

In [ ]:
pre_res.results

In [ ]:
out = []
for term in list(pre_res.results):
    out.append(
        [
            term,
            pre_res.results[term]["fdr"],
            pre_res.results[term]["es"],
            pre_res.results[term]["nes"],
        ]
    )

out_df = pd.DataFrame(
    out,
    columns=["Term", "fdr", "es", "nes"],
).sort_values(
    "fdr",
).reset_index(
    drop=True
)

out_df

In [ ]:
term_to_graph = out_df.iloc[0]["Term"]
term_to_graph

In [ ]:
gseaplot(
    pre_res.ranking,
    term=term_to_graph,
    **pre_res.results[term_to_graph],
)