In [ ]:
import pandas as pd

from analysis_shared_functions import (
    parse_heatmap_matrix_bamixchecker,
    long_df_to_matrix_bamixchecker,
    parse_sample_matching_results_bamixchecker,
    calculate_accuracy_metrics_pseudobulk
)
from visualization import all_samples_matrix_viz, bulk_vs_singlecell_matrix_viz

In [2]:
DATA_PATH = "../../data/output_data/"
FIGURES_PATH = "../../data/figures/"
tool = "BAMixChecker"
dataset = "low_grade_glioma"
pseudobulk = True
ncells = 100000
rd = 1

# Data munging

In [3]:
df, matrix = parse_heatmap_matrix_bamixchecker(DATA_PATH, pseudobulk, dataset, ncells)

In [4]:
df.head()

,Sample,Concordance Rate,Conclusion
0,,,
pseudobulk_GSM7326899_ncells_100000_2,pseudobulk_GSM7326899_ncells_100000_3,0.0,Unmatched
pseudobulk_GSM7326899_ncells_100000_2,pseudobulk_GSM7326899_ncells_100000_1,0.0,Unmatched
pseudobulk_GSM7326899_ncells_100000_2,pseudobulk_GSM7326890_ncells_100000_1,0.0,Unmatched
pseudobulk_GSM7326899_ncells_100000_2,pseudobulk_GSM7326890_ncells_100000_2,0.0,Unmatched
pseudobulk_GSM7326899_ncells_100000_2,pseudobulk_GSM7326890_ncells_100000_3,0.0,Unmatched

In [5]:
matrix.head()

,pseudobulk_GSM7326880_ncells_100000_1,pseudobulk_GSM7326880_ncells_100000_2,pseudobulk_GSM7326880_ncells_100000_3,pseudobulk_GSM7326881_ncells_100000_1,pseudobulk_GSM7326881_ncells_100000_2,pseudobulk_GSM7326881_ncells_100000_3,pseudobulk_GSM7326883_ncells_100000_1,pseudobulk_GSM7326883_ncells_100000_2,pseudobulk_GSM7326883_ncells_100000_3,pseudobulk_GSM7326884_ncells_100000_1,...,pseudobulk_GSM7326901_ncells_100000_3,pseudobulk_GSM7326902_ncells_100000_1,pseudobulk_GSM7326902_ncells_100000_2,pseudobulk_GSM7326902_ncells_100000_3,pseudobulk_GSM7326903_ncells_100000_1,pseudobulk_GSM7326903_ncells_100000_2,pseudobulk_GSM7326903_ncells_100000_3,pseudobulk_GSM7326905_ncells_100000_1,pseudobulk_GSM7326905_ncells_100000_2,pseudobulk_GSM7326905_ncells_100000_3
0,,,,,,,,,,,,,,,,,,,,,
pseudobulk_GSM7326880_ncells_100000_1,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
pseudobulk_GSM7326880_ncells_100000_2,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
pseudobulk_GSM7326880_ncells_100000_3,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
pseudobulk_GSM7326881_ncells_100000_1,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
pseudobulk_GSM7326881_ncells_100000_2,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
inferred_matches = parse_sample_matching_results_bamixchecker(DATA_PATH, pseudobulk, dataset, ncells)
inferred_matches.head()

,pseudobulk_GSM7326880_ncells_100000_1,pseudobulk_GSM7326880_ncells_100000_2,pseudobulk_GSM7326880_ncells_100000_3,pseudobulk_GSM7326881_ncells_100000_1,pseudobulk_GSM7326881_ncells_100000_2,pseudobulk_GSM7326881_ncells_100000_3,pseudobulk_GSM7326883_ncells_100000_1,pseudobulk_GSM7326883_ncells_100000_2,pseudobulk_GSM7326883_ncells_100000_3,pseudobulk_GSM7326884_ncells_100000_1,...,pseudobulk_GSM7326901_ncells_100000_3,pseudobulk_GSM7326902_ncells_100000_1,pseudobulk_GSM7326902_ncells_100000_2,pseudobulk_GSM7326902_ncells_100000_3,pseudobulk_GSM7326903_ncells_100000_1,pseudobulk_GSM7326903_ncells_100000_2,pseudobulk_GSM7326903_ncells_100000_3,pseudobulk_GSM7326905_ncells_100000_1,pseudobulk_GSM7326905_ncells_100000_2,pseudobulk_GSM7326905_ncells_100000_3
0,,,,,,,,,,,,,,,,,,,,,
pseudobulk_GSM7326880_ncells_100000_1,NaN,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
pseudobulk_GSM7326880_ncells_100000_2,0,NaN,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
pseudobulk_GSM7326880_ncells_100000_3,0,0,NaN,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
pseudobulk_GSM7326881_ncells_100000_1,0,0,0,NaN,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
pseudobulk_GSM7326881_ncells_100000_2,0,0,0,0,NaN,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
inferred_matches.shape

(66, 66)

# Real data viz & analysis

In [8]:
# bulk_vs_singlecell_matrix_viz(
#     matrix,
#     pseudobulk=pseudobulk,
#     tool=tool,
#     dataset=dataset,
#     ncells=ncells,
#     rd=rd,
#     save_fig=False
# )

## Comparison with expected matches

# Pseudobulk viz & analysis

In [9]:
# Filter BAMixChecker matrix to only samples ending in _1 in rows and samples ending in _2 in columns
pseudobulk_1 = "_1"
pseudobulk_2 = "_2"
matrix_filtered = matrix.loc[
    [idx for idx in matrix.index if idx.endswith(pseudobulk_1)],
    [col for col in matrix.columns if col.endswith(pseudobulk_2)]
]

In [ ]:
all_samples_matrix_viz(
    matrix_filtered, 
    pseudobulk=pseudobulk, 
    tool=tool, 
    dataset=dataset, 
    ncells=ncells, 
    rd=rd, 
    save_fig=False
)

In [11]:
# Create inferred_matches matrix for submatrix 
inferred_matches_filtered = inferred_matches.loc[
    [idx for idx in inferred_matches.index if idx.endswith(pseudobulk_1)],
    [col for col in inferred_matches.columns if col.endswith(pseudobulk_2)]
]

In [12]:
inferred_matches_filtered.head()

,pseudobulk_GSM7326880_ncells_100000_2,pseudobulk_GSM7326881_ncells_100000_2,pseudobulk_GSM7326883_ncells_100000_2,pseudobulk_GSM7326884_ncells_100000_2,pseudobulk_GSM7326885_ncells_100000_2,pseudobulk_GSM7326886_ncells_100000_2,pseudobulk_GSM7326887_ncells_100000_2,pseudobulk_GSM7326888_ncells_100000_2,pseudobulk_GSM7326890_ncells_100000_2,pseudobulk_GSM7326891_ncells_100000_2,...,pseudobulk_GSM7326894_ncells_100000_2,pseudobulk_GSM7326895_ncells_100000_2,pseudobulk_GSM7326896_ncells_100000_2,pseudobulk_GSM7326898_ncells_100000_2,pseudobulk_GSM7326899_ncells_100000_2,pseudobulk_GSM7326900_ncells_100000_2,pseudobulk_GSM7326901_ncells_100000_2,pseudobulk_GSM7326902_ncells_100000_2,pseudobulk_GSM7326903_ncells_100000_2,pseudobulk_GSM7326905_ncells_100000_2
0,,,,,,,,,,,,,,,,,,,,,
pseudobulk_GSM7326880_ncells_100000_1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
pseudobulk_GSM7326881_ncells_100000_1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
pseudobulk_GSM7326883_ncells_100000_1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
pseudobulk_GSM7326884_ncells_100000_1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
pseudobulk_GSM7326885_ncells_100000_1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
calculate_accuracy_metrics_pseudobulk(inferred_matches_filtered)

/Users/lathouwe/miniconda3/envs/analysis/lib/python3.14/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

(0.9545454545454546, 0.5, 0.0, 0.0, 0.0)