In [3]:
import pandas as pd

In [4]:
DATA_DIR = "../../../../../../Downloads"

In [41]:
df = pd.read_csv(f"{DATA_DIR}/master_variant_metadata_with_clinvar_and_depth.tsv", sep="\t")
df = df[df["chr"] == 17]

In [43]:
df.head()

,donor,gene,variant_id,chr,pos,ref,alt,clinvar_status,clnsig,pathogenic,...,polyA_mean_depth,depth_ratio,num_variants,num_clinvar,num_pathogenic,concordance_rate,chunk_gt,polyA_gt,chr_clean,num_discordant
1,2018,BRCA1,17_43169893_C_T,17,43169893,C,T,not_in_clinvar,NaN,False,...,14832276.5,1.638113,2,1,0,1.00,1/1,1/1,17,0
2,2023,BRCA1,17_43148782_C_A,17,43148782,C,A,not_in_clinvar,NaN,False,...,11212917.0,1.795239,1,0,0,1.00,1/1,1/1,17,0
4,2094,BRCA1,17_43135907_C_A,17,43135907,C,A,not_in_clinvar,NaN,False,...,9878690.5,1.878691,4,0,0,0.75,1/1,1/1,17,1
5,2094,BRCA1,17_43148782_C_A,17,43148782,C,A,not_in_clinvar,NaN,False,...,9878690.5,1.878691,4,0,0,0.75,0/1,0/1,17,1
6,2094,BRCA1,17_43166783_T_C,17,43166783,T,C,not_in_clinvar,NaN,False,...,9878690.5,1.878691,4,0,0,0.75,0/1,1/1,17,1

In [50]:
clinvar_brca1 = pd.read_csv(f"{DATA_DIR}/clinvar_result_brca1.txt", sep="\t")

In [53]:
clinvar_brca1.head()

,Name,Gene(s),Protein change,Condition(s),Accession,GRCh37Chromosome,GRCh37Location,GRCh38Chromosome,GRCh38Location,VariationID,...,Germline classification,Germline date last evaluated,Germline review status,Somatic clinical impact,Somatic clinical impact date last evaluated,Somatic clinical impact review status,Oncogenicity classification,Oncogenicity date last evaluated,Oncogenicity review status,Unnamed: 24
0,GRCh38/hg38 17q23.1-25.1(chr17:36449220-750531...,PPM1D|PPM1E|PPP1R1B|PPP1R9B|AARSD1|AATF|ABCA10...,NaN,See cases,VCV000148363,17,57595736 - 73049225,17,36449220 - 75053130,148363,...,Pathogenic,"Apr 21, 2011",no assertion criteria provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,GRCh38/hg38 17q21.33-24.2(chr17:36449220-68170...,LOC130061427|LOC130061428|LOC130061429|LOC1300...,NaN,See cases,VCV000057282,17,48563237 - 65936105,17,36449220 - 68170214,57282,...,Pathogenic,"Aug 12, 2011","criteria provided, single submitter",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,GRCh38/hg38 17q12-21.31(chr17:39199873-4562957...,NT5C3B|ODAD4|ORMDL3|P3H4|PGAP3|PLCD3|PLEKHH3|P...,NaN,See cases,VCV000058696,17,37356126 - 43706945,17,39199873 - 45629579,58696,...,Pathogenic,"Aug 12, 2011","criteria provided, single submitter",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NG_005905.2:g.(?_92501)_(135581_1441370)del(;)...,RND2|LOC110485084|LOC111589215|LOC111589216|LO...,NaN,"Breast-ovarian cancer, familial, susceptibilit...",VCV000373888,17|17,41176312 - 41277500,17|17,43024295 - 43125483,373888,...,Pathogenic,"Oct 2, 2015","criteria provided, single submitter",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NG_005905.2:g.(?_92501)_(135581_1441370)del,RND2|BRCA1|LOC110485084|LOC111589215|LOC111589...,NaN,"Breast-ovarian cancer, familial, susceptibilit...",VCV000373863,17,41176312 - 41277500,17,43024295 - 43125483,373863,...,Pathogenic,"Oct 2, 2015","criteria provided, single submitter",NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
clinvar_brca1.columns

Index(['Name', 'Gene(s)', 'Protein change', 'Condition(s)', 'Accession',
       'GRCh37Chromosome', 'GRCh37Location', 'GRCh38Chromosome',
       'GRCh38Location', 'VariationID', 'AlleleID(s)', 'dbSNP ID',
       'Canonical SPDI', 'Variant type', 'Molecular consequence',
       'Germline classification', 'Germline date last evaluated',
       'Germline review status', 'Somatic clinical impact',
       'Somatic clinical impact date last evaluated',
       'Somatic clinical impact review status', 'Oncogenicity classification',
       'Oncogenicity date last evaluated', 'Oncogenicity review status',
       'Unnamed: 24'],
      dtype='str')

In [55]:
clinvar_brca1 = clinvar_brca1[["Name", "GRCh38Location", 'VariationID', 'AlleleID(s)', 'Canonical SPDI', 'Variant type', 'Germline classification']]

In [56]:
clinvar_brca1[clinvar_brca1["Variant type"]=="single nucleotide variant"]

,Name,GRCh38Location,VariationID,AlleleID(s),Canonical SPDI,Variant type,Germline classification
6,NM_007294.3(BRCA1):c.*6207C>T,43039471,209219,206177,NC_000017.11:43039470:G:A,single nucleotide variant,Benign
7,NM_007294.3(BRCA1):c.*5860C>T,43039818,209220,206178,NC_000017.11:43039817:G:A,single nucleotide variant,Benign
9,NM_007294.3(BRCA1):c.*5513G>A,43040165,209222,206180,NC_000017.11:43040164:C:T,single nucleotide variant,Benign
10,NM_007294.3(BRCA1):c.*4549G>C,43041129,209223,206181,NC_000017.11:43041128:C:G,single nucleotide variant,Benign
11,NM_007294.3(BRCA1):c.*4271T>A,43041407,209224,206182,NC_000017.11:43041406:A:T,single nucleotide variant,Benign
...,...,...,...,...,...,...,...
15646,NM_007294.3:c.547+68A>G,NaN,4057255,4171186,NaN,single nucleotide variant,Benign
15782,U14680.1:n.562T>A,NaN,125869,131407,NaN,single nucleotide variant,Pathogenic
15784,U14680.1:n.5271+65G>A,NaN,125774,131312,NaN,single nucleotide variant,Uncertain significance
15789,U14680.1:n.2577G>A,NaN,125569,131107,NaN,single nucleotide variant,Uncertain significance
15793,U14680.1:n.2204C>T,NaN,125538,131076,NaN,single nucleotide variant,Uncertain significance

In [57]:
df["pos"] = df["pos"].astype(str)

In [58]:
pd.merge(df, clinvar_brca1, left_on="pos", right_on="GRCh38Location", how="inner")

,donor,gene,variant_id,chr,pos,ref,alt,clinvar_status,clnsig,pathogenic,...,polyA_gt,chr_clean,num_discordant,Name,GRCh38Location,VariationID,AlleleID(s),Canonical SPDI,Variant type,Germline classification
0,2221,BRCA1,17_43092919_G_A,17,43092919,G,A,in_clinvar,Benign,False,...,1/1,17,0,NM_007294.4(BRCA1):c.2612C>G (p.Pro871Arg),43092919,91594,97071,NC_000017.11:43092918:G:C,single nucleotide variant,Conflicting classifications of pathogenicity
1,2221,BRCA1,17_43092919_G_A,17,43092919,G,A,in_clinvar,Benign,False,...,1/1,17,0,NM_007294.4(BRCA1):c.2612delinsTT (p.Pro871fs),43092919,54620,69287,NC_000017.11:43092918:G:AA,Indel,Pathogenic
2,2221,BRCA1,17_43092919_G_A,17,43092919,G,A,in_clinvar,Benign,False,...,1/1,17,0,NM_007294.4(BRCA1):c.2612C>A (p.Pro871Gln),43092919,54618,69285,NC_000017.11:43092918:G:T,single nucleotide variant,Conflicting classifications of pathogenicity
3,2221,BRCA1,17_43092919_G_A,17,43092919,G,A,in_clinvar,Benign,False,...,1/1,17,0,NM_007294.4(BRCA1):c.2612C>T (p.Pro871Leu),43092919,41812,50251,NC_000017.11:43092918:G:A,single nucleotide variant,Benign