In [ ]:
import numpy as np
import pandas as pd

from sklearn.metrics import confusion_matrix

from analysis_shared_functions import (
    parse_heatmap_matrix_crosscheckfingerprints,
    long_df_to_matrix_crosscheckfingerprints,
    parse_sample_matching_results_crosscheckfingerprints,
    calculate_accuracy_metrics_pseudobulk
)
from visualization import all_samples_matrix_viz, bulk_vs_singlecell_matrix_viz

In [2]:
DATA_PATH = "../../data/output_data/"
FIGURES_PATH = "../../data/figures/"
tool = "CrosscheckFingerprints"
dataset = "low_grade_glioma"
pseudobulk = True
ncells = 500000
rd = 1

# Data munging

In [3]:
df, matrix = parse_heatmap_matrix_crosscheckfingerprints(DATA_PATH, pseudobulk, dataset, ncells, rd)

In [4]:
df.head()

,LEFT_SAMPLE,RIGHT_SAMPLE,LOD_SCORE,RESULT
0,pseudobulk_GSM7326894_ncells_500000_3,pseudobulk_GSM7326894_ncells_500000_3,15.275309,EXPECTED_MATCH
1,pseudobulk_GSM7326894_ncells_500000_3,pseudobulk_GSM7326880_ncells_500000_2,0.000000,INCONCLUSIVE
2,pseudobulk_GSM7326894_ncells_500000_3,pseudobulk_GSM7326888_ncells_500000_1,0.353664,UNEXPECTED_MATCH
3,pseudobulk_GSM7326894_ncells_500000_3,pseudobulk_GSM7326891_ncells_500000_2,0.565772,UNEXPECTED_MATCH
4,pseudobulk_GSM7326894_ncells_500000_3,pseudobulk_GSM7326901_ncells_500000_3,-3.725188,EXPECTED_MISMATCH

In [5]:
matrix.head()

,pseudobulk_GSM7326880_ncells_500000_1,pseudobulk_GSM7326880_ncells_500000_2,pseudobulk_GSM7326880_ncells_500000_3,pseudobulk_GSM7326881_ncells_500000_1,pseudobulk_GSM7326881_ncells_500000_2,pseudobulk_GSM7326881_ncells_500000_3,pseudobulk_GSM7326883_ncells_500000_1,pseudobulk_GSM7326883_ncells_500000_2,pseudobulk_GSM7326883_ncells_500000_3,pseudobulk_GSM7326884_ncells_500000_1,...,pseudobulk_GSM7326901_ncells_500000_3,pseudobulk_GSM7326902_ncells_500000_1,pseudobulk_GSM7326902_ncells_500000_2,pseudobulk_GSM7326902_ncells_500000_3,pseudobulk_GSM7326903_ncells_500000_1,pseudobulk_GSM7326903_ncells_500000_2,pseudobulk_GSM7326903_ncells_500000_3,pseudobulk_GSM7326905_ncells_500000_1,pseudobulk_GSM7326905_ncells_500000_2,pseudobulk_GSM7326905_ncells_500000_3
LEFT_SAMPLE,,,,,,,,,,,,,,,,,,,,,
pseudobulk_GSM7326880_ncells_500000_1,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
pseudobulk_GSM7326880_ncells_500000_2,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
pseudobulk_GSM7326880_ncells_500000_3,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
pseudobulk_GSM7326881_ncells_500000_1,0.0,0.0,0.0,0.144183,0.144183,0.144183,0.136719,0.136719,0.136719,0.0,...,-1.58695,0.146556,0.146556,0.146556,0.035495,0.035495,0.035495,0.146556,0.146556,0.146556
pseudobulk_GSM7326881_ncells_500000_2,0.0,0.0,0.0,0.144183,0.144183,0.144183,0.136719,0.136719,0.136719,0.0,...,-1.58695,0.146556,0.146556,0.146556,0.035495,0.035495,0.035495,0.146556,0.146556,0.146556

In [6]:
df["RESULT"].value_counts()["INCONCLUSIVE"]/df.shape[0]

np.float64(0.16735537190082644)

In [7]:
inferred_matches = parse_sample_matching_results_crosscheckfingerprints(DATA_PATH, pseudobulk, dataset, ncells, rd)
inferred_matches.head()

,pseudobulk_GSM7326880_ncells_500000_1,pseudobulk_GSM7326880_ncells_500000_2,pseudobulk_GSM7326880_ncells_500000_3,pseudobulk_GSM7326881_ncells_500000_1,pseudobulk_GSM7326881_ncells_500000_2,pseudobulk_GSM7326881_ncells_500000_3,pseudobulk_GSM7326883_ncells_500000_1,pseudobulk_GSM7326883_ncells_500000_2,pseudobulk_GSM7326883_ncells_500000_3,pseudobulk_GSM7326884_ncells_500000_1,...,pseudobulk_GSM7326901_ncells_500000_3,pseudobulk_GSM7326902_ncells_500000_1,pseudobulk_GSM7326902_ncells_500000_2,pseudobulk_GSM7326902_ncells_500000_3,pseudobulk_GSM7326903_ncells_500000_1,pseudobulk_GSM7326903_ncells_500000_2,pseudobulk_GSM7326903_ncells_500000_3,pseudobulk_GSM7326905_ncells_500000_1,pseudobulk_GSM7326905_ncells_500000_2,pseudobulk_GSM7326905_ncells_500000_3
LEFT_SAMPLE,,,,,,,,,,,,,,,,,,,,,
pseudobulk_GSM7326880_ncells_500000_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pseudobulk_GSM7326880_ncells_500000_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pseudobulk_GSM7326880_ncells_500000_3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pseudobulk_GSM7326881_ncells_500000_1,NaN,NaN,NaN,1,1,1,1,1,1,NaN,...,0,1,1,1,1,1,1,1,1,1
pseudobulk_GSM7326881_ncells_500000_2,NaN,NaN,NaN,1,1,1,1,1,1,NaN,...,0,1,1,1,1,1,1,1,1,1

In [9]:
inferred_matches.shape

(66, 66)

# Real data viz & analysis

In [ ]:
bulk_vs_singlecell_matrix_viz(
    matrix,
    pseudobulk=pseudobulk,
    tool=tool,
    dataset=dataset,
    ncells=ncells,
    rd=rd,
    save_fig=False
)

## Comparison with expected matches

In [ ]:
expected_matches_df = pd.read_csv(
    DATA_PATH + f"../metadata/sample_matches/sample_matches_{dataset}.csv"
).dropna(how="all", axis=1).dropna(how="any")

# Pseudobulk viz & analysis

In [10]:
# Filter CrosscheckFingerprints matrix to only samples ending in _1 in rows and samples ending in _2 in columns
pseudobulk_1 = "_1"
pseudobulk_2 = "_2"
pseudobulk_regex = r"_[1-3]{1}$"
matrix_filtered = matrix.loc[
    [idx for idx in matrix.index if idx.endswith(pseudobulk_1)],
    [col for col in matrix.columns if col.endswith(pseudobulk_2)]
]

In [11]:
# all_samples_matrix_viz(
#     matrix_filtered, 
#     pseudobulk=pseudobulk, 
#     tool=tool, 
#     dataset=dataset, 
#     ncells=ncells, 
#     rd=rd, 
#     save_fig=True,
#     FIGURES_PATH=FIGURES_PATH
# )

In [26]:
# Create inferred_matches matrix for submatrix 
inferred_matches_filtered = inferred_matches.loc[
    [idx for idx in inferred_matches.index if idx.endswith(pseudobulk_1)],
    [col for col in inferred_matches.columns if col.endswith(pseudobulk_2)]
]
inferred_matches_filtered.head()

,pseudobulk_GSM7326880_ncells_500000_2,pseudobulk_GSM7326881_ncells_500000_2,pseudobulk_GSM7326883_ncells_500000_2,pseudobulk_GSM7326884_ncells_500000_2,pseudobulk_GSM7326885_ncells_500000_2,pseudobulk_GSM7326886_ncells_500000_2,pseudobulk_GSM7326887_ncells_500000_2,pseudobulk_GSM7326888_ncells_500000_2,pseudobulk_GSM7326890_ncells_500000_2,pseudobulk_GSM7326891_ncells_500000_2,...,pseudobulk_GSM7326894_ncells_500000_2,pseudobulk_GSM7326895_ncells_500000_2,pseudobulk_GSM7326896_ncells_500000_2,pseudobulk_GSM7326898_ncells_500000_2,pseudobulk_GSM7326899_ncells_500000_2,pseudobulk_GSM7326900_ncells_500000_2,pseudobulk_GSM7326901_ncells_500000_2,pseudobulk_GSM7326902_ncells_500000_2,pseudobulk_GSM7326903_ncells_500000_2,pseudobulk_GSM7326905_ncells_500000_2
LEFT_SAMPLE,,,,,,,,,,,,,,,,,,,,,
pseudobulk_GSM7326880_ncells_500000_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pseudobulk_GSM7326881_ncells_500000_1,NaN,1,1,NaN,1,NaN,1,NaN,1,NaN,...,1,1,0,1,NaN,1,0,1,1,1
pseudobulk_GSM7326883_ncells_500000_1,NaN,1,1,0,0,NaN,0,0,0,NaN,...,1,0,0,0,1,1,0,0,1,1
pseudobulk_GSM7326884_ncells_500000_1,NaN,NaN,0,1,1,1,1,0,0,NaN,...,0,0,0,0,NaN,1,0,0,1,1
pseudobulk_GSM7326885_ncells_500000_1,NaN,1,0,1,1,NaN,1,1,1,NaN,...,1,1,1,1,1,1,0,1,1,1

In [ ]:
# Percentage NaNs
inferred_matches_filtered.isna().sum().sum()/(len(inferred_matches_filtered * inferred_matches_filtered.iloc[0]))

np.float64(3.6818181818181817)

In [ ]:
calculate_accuracy_metrics_pseudobulk(inferred_matches)

(0.5199724517906336,
 0.7339160839160839,
 0.029288702928870293,
 0.9545454545454546,
 0.05683355886332882)