In [ ]:
import pandas as pd

from analysis_shared_functions import (
    parse_heatmap_matrix_hysys,
    long_df_to_matrix_hysys,
    parse_sample_matching_results_hysys,
    calculate_accuracy_metrics_pseudobulk, 
)
from visualization import all_samples_matrix_viz, bulk_vs_singlecell_matrix_viz

In [2]:
DATA_PATH = "../../data/output_data/"
FIGURES_PATH = "../../data/figures/"
tool = "HYSYS"
dataset = "low_grade_glioma"
pseudobulk = True
ncells = 500000
rd = 1

# Data munging

In [3]:
df, matrix = parse_heatmap_matrix_hysys(DATA_PATH, pseudobulk, dataset, ncells, rd)

In [4]:
matrix.head()

,pseudobulk_GSM7326880_ncells_500000_1,pseudobulk_GSM7326880_ncells_500000_2,pseudobulk_GSM7326880_ncells_500000_3,pseudobulk_GSM7326881_ncells_500000_1,pseudobulk_GSM7326881_ncells_500000_2,pseudobulk_GSM7326881_ncells_500000_3,pseudobulk_GSM7326883_ncells_500000_1,pseudobulk_GSM7326883_ncells_500000_2,pseudobulk_GSM7326883_ncells_500000_3,pseudobulk_GSM7326884_ncells_500000_1,...,pseudobulk_GSM7326901_ncells_500000_3,pseudobulk_GSM7326902_ncells_500000_1,pseudobulk_GSM7326902_ncells_500000_2,pseudobulk_GSM7326902_ncells_500000_3,pseudobulk_GSM7326903_ncells_500000_1,pseudobulk_GSM7326903_ncells_500000_2,pseudobulk_GSM7326903_ncells_500000_3,pseudobulk_GSM7326905_ncells_500000_1,pseudobulk_GSM7326905_ncells_500000_2,pseudobulk_GSM7326905_ncells_500000_3
0,,,,,,,,,,,,,,,,,,,,,
pseudobulk_GSM7326880_ncells_500000_1,1.000,1.000,1.000,0.012,0.012,0.012,0.001,0.001,0.001,0.013,...,0.002,0.002,0.002,0.002,0.003,0.003,0.003,0.001,0.001,0.001
pseudobulk_GSM7326880_ncells_500000_2,1.000,1.000,1.000,0.012,0.012,0.012,0.001,0.001,0.001,0.013,...,0.002,0.002,0.002,0.002,0.003,0.003,0.003,0.001,0.001,0.001
pseudobulk_GSM7326880_ncells_500000_3,1.000,1.000,1.000,0.012,0.012,0.012,0.001,0.001,0.001,0.013,...,0.002,0.002,0.002,0.002,0.003,0.003,0.003,0.001,0.001,0.001
pseudobulk_GSM7326881_ncells_500000_1,0.012,0.012,0.012,1.000,1.000,1.000,0.001,0.001,0.001,0.021,...,0.006,0.003,0.003,0.003,0.006,0.006,0.006,0.001,0.001,0.001
pseudobulk_GSM7326881_ncells_500000_2,0.012,0.012,0.012,1.000,1.000,1.000,0.001,0.001,0.001,0.021,...,0.006,0.003,0.003,0.003,0.006,0.006,0.006,0.001,0.001,0.001

In [5]:
df.head()

,Sample,Concordance,Size
0,,,
pseudobulk_GSM7326880_ncells_500000_1,pseudobulk_GSM7326880_ncells_500000_1,1.000,1380
pseudobulk_GSM7326880_ncells_500000_1,pseudobulk_GSM7326880_ncells_500000_2,1.000,1380
pseudobulk_GSM7326880_ncells_500000_1,pseudobulk_GSM7326880_ncells_500000_3,1.000,1380
pseudobulk_GSM7326880_ncells_500000_1,pseudobulk_GSM7326881_ncells_500000_1,0.012,3364
pseudobulk_GSM7326880_ncells_500000_1,pseudobulk_GSM7326881_ncells_500000_2,0.012,3364

In [6]:
inferred_matches = parse_sample_matching_results_hysys(DATA_PATH, pseudobulk, dataset, ncells, rd)
inferred_matches.head()

sample2,pseudobulk_GSM7326880_ncells_500000_1,pseudobulk_GSM7326880_ncells_500000_2,pseudobulk_GSM7326880_ncells_500000_3,pseudobulk_GSM7326881_ncells_500000_1,pseudobulk_GSM7326881_ncells_500000_2,pseudobulk_GSM7326881_ncells_500000_3,pseudobulk_GSM7326883_ncells_500000_1,pseudobulk_GSM7326883_ncells_500000_2,pseudobulk_GSM7326883_ncells_500000_3,pseudobulk_GSM7326884_ncells_500000_1,...,pseudobulk_GSM7326901_ncells_500000_3,pseudobulk_GSM7326902_ncells_500000_1,pseudobulk_GSM7326902_ncells_500000_2,pseudobulk_GSM7326902_ncells_500000_3,pseudobulk_GSM7326903_ncells_500000_1,pseudobulk_GSM7326903_ncells_500000_2,pseudobulk_GSM7326903_ncells_500000_3,pseudobulk_GSM7326905_ncells_500000_1,pseudobulk_GSM7326905_ncells_500000_2,pseudobulk_GSM7326905_ncells_500000_3
sample1,,,,,,,,,,,,,,,,,,,,,
pseudobulk_GSM7326880_ncells_500000_1,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
pseudobulk_GSM7326880_ncells_500000_2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
pseudobulk_GSM7326880_ncells_500000_3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
pseudobulk_GSM7326881_ncells_500000_1,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
pseudobulk_GSM7326881_ncells_500000_2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
inferred_matches.shape

(66, 66)

# Real data viz & analysis

## Comparison with expected matches

# Pseudobulk data viz & analysis

In [ ]:
# Filter HYSYS matrix to only samples ending in _1 in rows and samples ending in _2 in columns (or _2 vs _3 or _1 vs _3)
pseudobulk_1 = "_1"
pseudobulk_2 = "_2"
matrix_filtered = matrix.loc[
    [idx for idx in matrix.index if idx.endswith(pseudobulk_1)],
    [col for col in matrix.columns if col.endswith(pseudobulk_2)]
]

all_samples_matrix_viz(
    matrix_filtered, 
    pseudobulk=pseudobulk, 
    tool=tool, 
    dataset=dataset, 
    ncells=ncells, 
    rd=rd, 
    save_fig=True,
    FIGURES_PATH=FIGURES_PATH
)

In [9]:
inferred_matches_filtered = inferred_matches.loc[
    [idx for idx in inferred_matches.index if idx.endswith(pseudobulk_1)],
    [col for col in inferred_matches.columns if col.endswith(pseudobulk_2)]
]
inferred_matches_filtered.head()

sample2,pseudobulk_GSM7326880_ncells_500000_2,pseudobulk_GSM7326881_ncells_500000_2,pseudobulk_GSM7326883_ncells_500000_2,pseudobulk_GSM7326884_ncells_500000_2,pseudobulk_GSM7326885_ncells_500000_2,pseudobulk_GSM7326886_ncells_500000_2,pseudobulk_GSM7326887_ncells_500000_2,pseudobulk_GSM7326888_ncells_500000_2,pseudobulk_GSM7326890_ncells_500000_2,pseudobulk_GSM7326891_ncells_500000_2,...,pseudobulk_GSM7326894_ncells_500000_2,pseudobulk_GSM7326895_ncells_500000_2,pseudobulk_GSM7326896_ncells_500000_2,pseudobulk_GSM7326898_ncells_500000_2,pseudobulk_GSM7326899_ncells_500000_2,pseudobulk_GSM7326900_ncells_500000_2,pseudobulk_GSM7326901_ncells_500000_2,pseudobulk_GSM7326902_ncells_500000_2,pseudobulk_GSM7326903_ncells_500000_2,pseudobulk_GSM7326905_ncells_500000_2
sample1,,,,,,,,,,,,,,,,,,,,,
pseudobulk_GSM7326880_ncells_500000_1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
pseudobulk_GSM7326881_ncells_500000_1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
pseudobulk_GSM7326883_ncells_500000_1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
pseudobulk_GSM7326884_ncells_500000_1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
pseudobulk_GSM7326885_ncells_500000_1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
calculate_accuracy_metrics_pseudobulk(inferred_matches)

(0.9696969696969697, 0.49230769230769234, 0.0, 0.0, nan)