In [34]:
import numpy as np
import pandas as pd

from sklearn.metrics import confusion_matrix

from analysis_shared_functions import (
    parse_heatmap_matrix_ngscheckmate, 
    long_df_to_matrix_ngscheckmate,
    parse_sample_matching_results_ngscheckmate,
    calculate_accuracy_metrics_pseudobulk
)
from visualization import all_samples_matrix_viz, bulk_vs_singlecell_matrix_viz

In [35]:
DATA_PATH = "../../data/output_data/"
FIGURES_PATH = "../../data/figures/"
tool = "NGSCheckmate"
dataset = "low_grade_glioma"
pseudobulk = True
ncells = 100000
rd = 1

# Data munging

In [36]:
df, matrix = parse_heatmap_matrix_ngscheckmate(DATA_PATH, pseudobulk, dataset, ncells, rd)

In [37]:
df.head()

,Matched,Sample,Binary,Correlation
0,,,,
pseudobulk_GSM7326880_ncells_100000_1,matched,pseudobulk_GSM7326880_ncells_100000_2,1.0000,0.0
pseudobulk_GSM7326880_ncells_100000_1,matched,pseudobulk_GSM7326880_ncells_100000_3,1.0000,0.0
pseudobulk_GSM7326880_ncells_100000_1,unmatched,pseudobulk_GSM7326881_ncells_100000_1,0.1674,0.0
pseudobulk_GSM7326880_ncells_100000_1,unmatched,pseudobulk_GSM7326881_ncells_100000_2,0.1674,0.0
pseudobulk_GSM7326880_ncells_100000_1,unmatched,pseudobulk_GSM7326881_ncells_100000_3,0.1674,0.0

In [38]:
matrix.head()

,pseudobulk_GSM7326880_ncells_100000_1,pseudobulk_GSM7326880_ncells_100000_2,pseudobulk_GSM7326880_ncells_100000_3,pseudobulk_GSM7326881_ncells_100000_1,pseudobulk_GSM7326881_ncells_100000_2,pseudobulk_GSM7326881_ncells_100000_3,pseudobulk_GSM7326883_ncells_100000_1,pseudobulk_GSM7326883_ncells_100000_2,pseudobulk_GSM7326883_ncells_100000_3,pseudobulk_GSM7326884_ncells_100000_1,...,pseudobulk_GSM7326901_ncells_100000_3,pseudobulk_GSM7326902_ncells_100000_1,pseudobulk_GSM7326902_ncells_100000_2,pseudobulk_GSM7326902_ncells_100000_3,pseudobulk_GSM7326903_ncells_100000_1,pseudobulk_GSM7326903_ncells_100000_2,pseudobulk_GSM7326903_ncells_100000_3,pseudobulk_GSM7326905_ncells_100000_1,pseudobulk_GSM7326905_ncells_100000_2,pseudobulk_GSM7326905_ncells_100000_3
0,,,,,,,,,,,,,,,,,,,,,
pseudobulk_GSM7326880_ncells_100000_1,NaN,0.0,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
pseudobulk_GSM7326880_ncells_100000_2,0.0,NaN,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
pseudobulk_GSM7326880_ncells_100000_3,0.0,0.0,NaN,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
pseudobulk_GSM7326881_ncells_100000_1,0.0,0.0,0.0,NaN,0.0001,0.0001,0.0001,0.0001,0.0001,0.0001,...,0.0,0.0,0.0,0.0,0.0001,0.0001,0.0001,0.0001,0.0001,0.0001
pseudobulk_GSM7326881_ncells_100000_2,0.0,0.0,0.0,0.0001,NaN,0.0001,0.0001,0.0001,0.0001,0.0001,...,0.0,0.0,0.0,0.0,0.0001,0.0001,0.0001,0.0001,0.0001,0.0001

In [39]:
inferred_matches = parse_sample_matching_results_ngscheckmate(DATA_PATH, pseudobulk, dataset, ncells, rd)
inferred_matches.head()

,pseudobulk_GSM7326880_ncells_100000_1,pseudobulk_GSM7326880_ncells_100000_2,pseudobulk_GSM7326880_ncells_100000_3,pseudobulk_GSM7326881_ncells_100000_1,pseudobulk_GSM7326881_ncells_100000_2,pseudobulk_GSM7326881_ncells_100000_3,pseudobulk_GSM7326883_ncells_100000_1,pseudobulk_GSM7326883_ncells_100000_2,pseudobulk_GSM7326883_ncells_100000_3,pseudobulk_GSM7326884_ncells_100000_1,...,pseudobulk_GSM7326901_ncells_100000_3,pseudobulk_GSM7326902_ncells_100000_1,pseudobulk_GSM7326902_ncells_100000_2,pseudobulk_GSM7326902_ncells_100000_3,pseudobulk_GSM7326903_ncells_100000_1,pseudobulk_GSM7326903_ncells_100000_2,pseudobulk_GSM7326903_ncells_100000_3,pseudobulk_GSM7326905_ncells_100000_1,pseudobulk_GSM7326905_ncells_100000_2,pseudobulk_GSM7326905_ncells_100000_3
0,,,,,,,,,,,,,,,,,,,,,
pseudobulk_GSM7326880_ncells_100000_1,NaN,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
pseudobulk_GSM7326880_ncells_100000_2,1,NaN,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
pseudobulk_GSM7326880_ncells_100000_3,1,1,NaN,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
pseudobulk_GSM7326881_ncells_100000_1,0,0,0,NaN,1,1,0,0,0,0,...,1,0,0,0,0,1,0,0,0,0
pseudobulk_GSM7326881_ncells_100000_2,0,0,0,1,NaN,1,0,0,0,0,...,1,0,0,0,0,1,0,0,0,0

In [40]:
inferred_matches.shape

(66, 66)

# Real data viz & analysis

In [ ]:
bulk_vs_singlecell_matrix_viz(
    matrix,
    pseudobulk=pseudobulk,
    tool=tool,
    dataset=dataset,
    ncells=ncells,
    rd=rd,
    save_fig=False
)

## Comparison with expected matches

# Pseudobulk viz & analysis

In [41]:
# Filter NGSCheckmate matrix to only samples ending in _1 in rows and samples ending in _2 in columns (or _2 vs _3 or _1 vs _3)
pseudobulk_1 = "_1"
pseudobulk_2 = "_2"
matrix_filtered = matrix.loc[
    [idx for idx in matrix.index if idx.endswith(pseudobulk_1)],
    [col for col in matrix.columns if col.endswith(pseudobulk_2)]
]

all_samples_matrix_viz(
    matrix_filtered, 
    pseudobulk=pseudobulk, 
    tool=tool, 
    dataset=dataset, 
    ncells=ncells, 
    rd=rd, 
    save_fig=True,
    FIGURES_PATH=FIGURES_PATH
)

In [42]:
# Filter NGSCheckmate sample matches matrix to only samples ending in _1 in rows and samples ending in _2 in columns (or _2 vs _3 or _1 vs _3)
inferred_matches_filtered = inferred_matches.loc[
    [idx for idx in inferred_matches.index if idx.endswith(pseudobulk_1)],
    [col for col in inferred_matches.columns if col.endswith(pseudobulk_2)]
]
inferred_matches_filtered.head()

,pseudobulk_GSM7326880_ncells_100000_2,pseudobulk_GSM7326881_ncells_100000_2,pseudobulk_GSM7326883_ncells_100000_2,pseudobulk_GSM7326884_ncells_100000_2,pseudobulk_GSM7326885_ncells_100000_2,pseudobulk_GSM7326886_ncells_100000_2,pseudobulk_GSM7326887_ncells_100000_2,pseudobulk_GSM7326888_ncells_100000_2,pseudobulk_GSM7326890_ncells_100000_2,pseudobulk_GSM7326891_ncells_100000_2,...,pseudobulk_GSM7326894_ncells_100000_2,pseudobulk_GSM7326895_ncells_100000_2,pseudobulk_GSM7326896_ncells_100000_2,pseudobulk_GSM7326898_ncells_100000_2,pseudobulk_GSM7326899_ncells_100000_2,pseudobulk_GSM7326900_ncells_100000_2,pseudobulk_GSM7326901_ncells_100000_2,pseudobulk_GSM7326902_ncells_100000_2,pseudobulk_GSM7326903_ncells_100000_2,pseudobulk_GSM7326905_ncells_100000_2
0,,,,,,,,,,,,,,,,,,,,,
pseudobulk_GSM7326880_ncells_100000_1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
pseudobulk_GSM7326881_ncells_100000_1,0,1,0,0,0,0,1,0,0,0,...,0,1,1,0,0,0,1,0,1,0
pseudobulk_GSM7326883_ncells_100000_1,0,0,1,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
pseudobulk_GSM7326884_ncells_100000_1,0,0,0,1,0,1,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
pseudobulk_GSM7326885_ncells_100000_1,0,0,0,0,1,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,0

In [ ]:
calculate_accuracy_metrics_pseudobulk(inferred_matches_filtered)

(0.8367768595041323,
 0.8495670995670996,
 0.2,
 0.8636363636363636,
 0.32478632478632474)