In [1]:
import pandas as pd

In [2]:
DATA_PATH = "/Users/lathouwe/Downloads"

In [5]:
read_depth_files = [
    "coverage_central_nervous_system_tumor_bulk.txt",
    "coverage_hgsoc_bulk_chunk_ribo.txt",
    "coverage_hgsoc_bulk_dissociated_polyA.txt",
    "coverage_hgsoc_bulk_dissociated_ribo.txt",
    "coverage_hgsoc_new_bulk_chunk_ribo.txt",
    "coverage_hgsoc_new_bulk_diss_polyA.txt",
    "coverage_hgsoc_single-cell.txt",
    "coverage_high_grade_glioma_bulk.txt",
    "coverage_high_grade_glioma_single-cell.txt",
    "coverage_low_grade_glioma_bulk.txt",
    "coverage_low_grade_glioma_single-cell.txt",
    ]

In [6]:
full_df = pd.DataFrame()

for file in read_depth_files:
    df = pd.read_csv(f"{DATA_PATH}/{file}", sep="\t")
    df = df[df["#rname"].str.contains(f"chr\\d", regex=True)]
    mean_depth = df["meandepth"].mean()
    full_df = pd.concat([full_df, pd.DataFrame({
        "file": [file],
        "mean_depth": [mean_depth],
    })], ignore_index=True)

full_df["file"] = full_df["file"].str.replace("coverage_", "").str.replace(".txt", "")
full_df["dataset"] = full_df["file"].str.extract(r"^(.*)_(?:bulk|single-cell)")
full_df["datatype"] = full_df["file"].str.extract(
    r"_(bulk|single-cell|bulk_chunk_ribo|bulk_diss_polyA|bulk_dissociated_ribo|bulk_dissociated_polyA)$"
    )
full_df.sort_values("mean_depth")

,file,mean_depth,dataset,datatype
8,high_grade_glioma_single-cell,3.049232,high_grade_glioma,single-cell
10,low_grade_glioma_single-cell,3.471983,low_grade_glioma,single-cell
9,low_grade_glioma_bulk,4.723560,low_grade_glioma,bulk
6,hgsoc_single-cell,6.796843,hgsoc,single-cell
0,central_nervous_system_tumor_bulk,19.903832,central_nervous_system_tumor,bulk
3,hgsoc_bulk_dissociated_ribo,28.242141,hgsoc,bulk_dissociated_ribo
1,hgsoc_bulk_chunk_ribo,29.990427,hgsoc,bulk_chunk_ribo
2,hgsoc_bulk_dissociated_polyA,34.575459,hgsoc,bulk_dissociated_polyA
5,hgsoc_new_bulk_diss_polyA,57.185059,hgsoc_new,bulk_diss_polyA
7,high_grade_glioma_bulk,58.058427,high_grade_glioma,bulk
4,hgsoc_new_bulk_chunk_ribo,103.581450,hgsoc_new,bulk_chunk_ribo

In [7]:
df = pd.read_csv(f"{DATA_PATH}/coverage_high_grade_glioma_bulk.txt", sep="\t")
df = df[df["#rname"].str.contains(f"chr\\d", regex=True)]
df

,#rname,startpos,endpos,numreads,covbases,coverage,meandepth,meanbaseq,meanmapq
0,chr1,1,248956422,119438264,85122285,34.1916,67.1265,36.3,242.0
1,chr10,1,133797422,36258108,42440041,31.7196,38.0360,36.3,251.0
2,chr11,1,135086622,61832657,44392621,32.8623,64.2544,36.3,252.0
3,chr12,1,133275309,69877871,45012520,33.7741,73.5872,36.5,246.0
4,chr13,1,114364328,13548195,21769357,19.0351,16.6198,36.3,250.0
5,chr14,1,107043718,28903975,29078454,27.1650,37.9045,36.2,252.0
6,chr15,1,101991189,31262190,32743147,32.1039,42.9547,36.4,249.0
7,chr16,1,90338345,46735331,31313227,34.6622,72.5300,36.2,239.0
8,chr17,1,83257441,78570956,38465374,46.2005,132.7130,36.2,251.0
9,chr18,1,80373285,11998420,19042271,23.6923,20.9426,36.2,251.0
10,chr19,1,58617616,81496039,33148792,56.5509,194.7210,36.1,253.0
11,chr2,1,242193529,68637184,75738242,31.2718,39.7470,36.5,251.0
12,chr20,1,64444167,31602331,23197010,35.9955,68.8544,36.3,251.0
13,chr21,1,46709983,21417853,12227958,26.1785,64.1108,37.2,140.0
14,chr22,1,50818468,24864919,17814036,35.0543,68.6401,36.2,250.0
15,chr3,1,198295559,51734998,61704959,31.1177,36.5945,36.3,252.0
16,chr4,1,190214555,34030495,45686530,24.0184,25.1015,36.5,252.0
17,chr5,1,181538259,51738319,49701579,27.3780,39.9491,36.5,249.0
18,chr6,1,170805979,53992402,47995665,28.0995,44.3114,36.3,243.0
19,chr7,1,159345973,58492444,53253891,33.4203,51.4839,36.2,244.0
20,chr8,1,145138636,37101208,39972144,27.5407,35.8853,36.4,251.0
21,chr9,1,138394717,40752286,42241025,30.5221,41.2177,36.2,242.0