In [1]:
import pandas as pd
import re

In [2]:
trace_file_1 = "../benchmarking/data/trace-20260925-55780271.txt"
trace_file_2 = "../benchmarking/data/trace-20260927-36157097.txt"
trace_file_3 = "../benchmarking/data/trace-20260928-46628641.txt"
trace_file_4 = "../benchmarking/data/trace-20261012-65746150.txt"

In [3]:
trace_df = pd.read_csv(trace_file_1, delimiter="\t")
trace_extra = pd.read_csv(trace_file_2, delimiter="\t")
trace_ntsm = pd.read_csv(trace_file_3, delimiter="\t")
trace_conpair = pd.read_csv(trace_file_4, delimiter="\t")

In [4]:
trace_extra = trace_extra[trace_extra["name"] == "CROSSCHECK_FINGERPRINTS"]
trace_df = trace_df[trace_df["status"] != "FAILED"]
trace_conpair = trace_conpair[trace_conpair["status"] != "CACHED"]

In [6]:
trace_df = pd.concat([trace_df, trace_extra, trace_ntsm, trace_conpair], ignore_index=True)

In [7]:
# Convert time to seconds
trace_df["realtime"] = pd.to_timedelta(trace_df["realtime"]).dt.total_seconds()
trace_df["duration"] = pd.to_timedelta(trace_df["duration"]).dt.total_seconds()

In [13]:
def convert_size_to_gb(val):
    if pd.isna(val):
        return None
    
    # Clean and split string into numeric part and unit part
    val_str = str(val).strip().lower()
    match = re.match(r'^([\d.]+)\s*([a-z]+)$', val_str)
    
    if not match:
        return float('nan')
    
    num, unit = float(match.group(1)), match.group(2)
    
    # Define multipliers to convert everything to GB
    if unit in ['MB', 'mb', 'm']:
        return num / 1024  # Convert MB to GB
    elif unit in ['GB', 'gb', 'g']:
        return num
    elif unit in ['KB', 'kb', 'k']:
        return num / (1024 ** 2)  # Convert KB to GB
    elif unit in ["B", "b"]:
        return num / (1024 ** 3)  # Convert Bytes to GB
    
    return num

In [14]:
trace_df[trace_df["name"].str.contains("CONPAIR_VERIFY")]

,task_id,hash,native_id,name,status,exit,submit,duration,realtime,%cpu,peak_rss,peak_vmem,rchar,wchar
1641,138,c6/e16e01,33954797,CONPAIR_VERIFY (2),COMPLETED,0,2026-10-12 18:49:59.987,178.0,21.3,5.3%,115.7 MB,1.5 GB,22 MB,544 B
1642,139,0d/7759cf,33954802,CONPAIR_VERIFY (3),COMPLETED,0,2026-10-12 18:50:02.931,175.0,9.3,15.2%,114.5 MB,1.5 GB,22 MB,544 B
1643,141,5f/6ff851,33954805,CONPAIR_VERIFY (5),COMPLETED,0,2026-10-12 18:50:04.575,173.0,11.8,15.7%,107.9 MB,1.5 GB,22.2 MB,528 B
1644,137,f0/d4f45c,33954801,CONPAIR_VERIFY (1),COMPLETED,0,2026-10-12 18:50:02.721,175.0,2.0,64.9%,88 MB,1.5 GB,22.2 MB,529 B
1645,140,2f/8fd2f9,33954803,CONPAIR_VERIFY (4),COMPLETED,0,2026-10-12 18:50:03.749,174.0,18.7,11.1%,101.1 MB,1.5 GB,22 MB,528 B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2788,903,ab/bf1c30,33960593,CONPAIR_VERIFY (767),COMPLETED,0,2026-10-12 19:55:35.128,44.4,1.9,79.6%,101.8 MB,1.5 GB,21.9 MB,532 B
2789,1053,b2/bdf3f5,33960594,CONPAIR_VERIFY (917),COMPLETED,0,2026-10-12 19:55:35.187,44.3,2.0,81.7%,95.2 MB,1.5 GB,22.1 MB,532 B
2790,1054,57/ff2c40,33960595,CONPAIR_VERIFY (918),COMPLETED,0,2026-10-12 19:55:35.236,44.3,1.9,80.9%,101.9 MB,1.5 GB,22 MB,532 B
2791,1070,af/6b23c2,33960606,CONPAIR_VERIFY (934),COMPLETED,0,2026-10-12 19:55:44.533,35.0,3.1,32.1%,89.6 MB,1.5 GB,22.3 MB,528 B
2792,816,f3/181148,33960589,CONPAIR_VERIFY (680),COMPLETED,0,2026-10-12 19:55:34.551,49.9,1.5,64.6%,122.7 MB,1.5 GB,22 MB,531 B

In [15]:
# Analyze the computational burden for a single process
# Let's start with PREPARE_INPUTS
# We'll build up a df that has a different process in each row and columns for various metrics like realtime and peak_rss
# Columns will be: process, n (number of occurrences), mean realtime (total time in seconds), mean peak_rss (maximum memory usage in MB), mean %cpu, mean rchar in GB, mean wchar in GB
processes = [
    "PREPARE_INPUTS", "GENOTYPE_INDIVIDUAL", "MERGE", "FILTER_BAM",
    "SNP_REF", "CROSSCHECK", "HYSYS", "NGSCHECKMATE", "PEDDY", "TIMEATTACK",
    "OMICSPRINT", "CONPAIR_PILEUP", "CONPAIR_VERIFY", "SOMALIER_EXTRACT", "SOMALIER_RELATE", 
    "NTSM_COUNT", "NTSM_EVAL", "VIREO"
    ] 
metrics_df = pd.DataFrame()

for process in processes:
    process_df = trace_df[trace_df["name"].str.contains(process)]
    n = len(process_df)
    mean_realtime = process_df["realtime"].mean()
    mean_peak_rss = process_df["peak_rss"].apply(convert_size_to_gb).astype(float).mean()  # Convert to GB
    mean_cpu = process_df["%cpu"].str.rstrip("%").astype(float).mean()
    mean_rchar = process_df["rchar"].apply(convert_size_to_gb).astype(float).mean()  # Convert to GB
    mean_wchar = process_df["wchar"].apply(convert_size_to_gb).astype(float).mean()  # Convert to GB
    metrics_df = pd.concat([
        metrics_df, 
        pd.DataFrame([{
        "process": process,
        "n": n,
        "mean realtime (s)": mean_realtime,
        "mean peak_rss (GB)": mean_peak_rss,
        "mean %cpu": mean_cpu,
        "mean rchar (GB)": mean_rchar,
        "mean wchar (GB)": mean_wchar
    }])])

metrics_df

,process,n,mean realtime (s),mean peak_rss (GB),mean %cpu,mean rchar (GB),mean wchar (GB)
0,PREPARE_INPUTS,68,23.873294,0.027008,92.770588,3.467172,3.265740e-03
0,GENOTYPE_INDIVIDUAL,68,391.691176,0.490523,102.114706,7.130882,7.163747e-01
0,MERGE,1,571.000000,0.626465,56.500000,2.900000,6.438477e-01
0,FILTER_BAM,68,313.394441,0.022952,95.744118,6.070817,2.606835e+00
0,SNP_REF,1,41.600000,0.692773,70.700000,2.200000,1.900000e+00
0,CROSSCHECK,2,67.000000,0.546191,138.900000,1.800000,1.500000e+00
0,HYSYS,1,441.000000,1.300000,50.500000,2.800000,2.600000e+00
0,NGSCHECKMATE,1,222.000000,0.149414,8.600000,1.400000,1.100000e+00
0,PEDDY,1,84.000000,0.662988,9.700000,0.912500,4.003906e-03
0,TIMEATTACK,0,NaN,NaN,NaN,NaN,NaN
0,OMICSPRINT,1,186.000000,5.800000,99.600000,2.300000,2.000000e+00
0,CONPAIR_PILEUP,68,78.910294,0.570458,74.569118,5.327941,1.157747e-03
0,CONPAIR_VERIFY,1152,3.465143,0.101326,47.912066,0.021633,4.928192e-07
0,SOMALIER_EXTRACT,68,97.970588,0.536347,95.016176,10.427941,1.300000e+00
0,SOMALIER_RELATE,1,27.200000,0.057813,2.700000,0.049414,9.606361e-04
0,NTSM_COUNT,136,231.044118,0.176435,183.767647,8.854412,4.416176e+00
0,NTSM_EVAL,2,14.300000,0.121582,36.200000,0.141797,5.817413e-06
0,VIREO,1,468.000000,27.100000,91.000000,0.112109,3.337860e-05

In [11]:
metrics_df.to_csv("computational_burden_averages_hgsoc.csv", index=False)

In [83]:
trace_df[trace_df["name"].str.contains("GENOTYPE_INDIVIDUAL")]["peak_rss"].str.rstrip(" MB").astype(float).describe()

count     68.000000
mean     502.295588
std        4.789959
min      494.100000
25%      499.900000
50%      501.000000
75%      503.850000
max      523.600000
Name: peak_rss, dtype: float64